import React from 'react'
import Head from 'next/head'

function MainPage() {
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto ">
                <Side
                bar />

        <Feed/>
        {
          isOpen &&      <Modal/>
        }
  
      </main>
    </div>
  )
}

export default MainPage