import Head from "next/head";
import Sidebar from "../components/sidebar";

export default function Home() {
  return (
    <div className="w-[200px] h-[200px] bg-red-400">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto ">
        <Sidebar />
      </main>
    </div>
  );
}
