import Head from "next/head";
import Sidebar from "../components/sidebar";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      homeeeee
      <main className="bg-black">
        <Sidebar />
      </main>
    </div>
  );
}
